--------------------------------------------------------
--  DDL for Table LOAN_APPLICATIONS
--------------------------------------------------------
  CREATE TABLE "LOAN_APPLICATIONS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY, 
	"STUDENT_NAME" VARCHAR2(100 BYTE), 
	"LOAN_AMOUNT" NUMBER(15,2), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'PENDING', 
	"APPLICATION_DATE" DATE DEFAULT SYSDATE, 
	"PURPOSE" VARCHAR2(100 BYTE), 
	"TERM" NUMBER, 
	"INTEREST_RATE" NUMBER(5,2)
   ) 
--------------------------------------------------------
-- INSERT THE BELOW DUMMY APPLICATIONS DATA
--------------------------------------------------------
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Alice Johnson',15000,'PENDING',to_date('01-MAR-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Angela Martin',35000,'PENDING',to_date('08-MAR-24','DD-MON-RR'),'PhD',48,4.95);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Bob Smith',20000,'PENDING',to_date('15-FEB-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('David Lee',22000,'PENDING',to_date('05-MAR-24','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Emma Davis',25000,'APPROVED',to_date('30-JAN-24','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Michael Scott',30000,'APPROVED',to_date('28-FEB-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Jim Halpert',40000,'APPROVED',to_date('25-JAN-24','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Pam Beesly',18000,'REJECTED',to_date('10-FEB-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Dwight Schrute',35000,'REJECTED',to_date('03-MAR-24','DD-MON-RR'),'PhD',48,4.95);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Kevin Malone',28000,'PENDING',to_date('10-MAR-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Stanley Hudson',42000,'REJECTED',to_date('12-MAR-24','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Grey Matter',53000,'APPROVED',to_date('10-MAR-25','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Peter Parker',15000,'APPROVED',to_date('08-MAR-25','DD-MON-RR'),'PhD',48,4.95);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('John Snow',35000,'APPROVED',to_date('12-MAR-25','DD-MON-RR'),'PhD',48,4.95);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Oscar Martinez',30000,'PENDING',to_date('05-MAR-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Meredith Palmer',40000,'APPROVED',to_date('02-MAR-24','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Oscar Martinez',30000,'PENDING',to_date('05-MAR-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Meredith Palmer',40000,'APPROVED',to_date('02-MAR-24','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into LOAN_APPLICATIONS (STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values ('Ryan Howard',25000,'REJECTED',to_date('10-MAR-24','DD-MON-RR'),'PhD',48,4.95);
--------------------------------------------------------
--  DDL for Table users
--------------------------------------------------------
  CREATE TABLE "users" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE)
   )
--------------------------------------------------------
--  DDL for Table BANK_DATA
--------------------------------------------------------
  CREATE TABLE "BANK_DATA" 
   (	"PORTFOLIO_AMOUNT" NUMBER(20,2)
   )
--------------------------------------------------------
    INSERT INTO BANK_DATA (PORTFOLIO_AMOUNT) 
    VALUES (5500000); 
--------------------------------------------------------
   
   