--------------------------------------------------------
--  File created - Sunday-March-16-2025   
--------------------------------------------------------
REM INSERTING into SYS.LOAN_APPLICATIONS
SET DEFINE OFF;
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (1,'Alice Johnson',15000,'PENDING',to_date('01-MAR-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (27,'Angela Martin',35000,'PENDING',to_date('08-MAR-24','DD-MON-RR'),'PhD',48,4.95);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (3,'Bob Smith',20000,'PENDING',to_date('15-FEB-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (5,'David Lee',22000,'PENDING',to_date('05-MAR-24','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (6,'Emma Davis',25000,'APPROVED',to_date('30-JAN-24','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (22,'Michael Scott',30000,'APPROVED',to_date('28-FEB-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (23,'Jim Halpert',40000,'APPROVED',to_date('25-JAN-24','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (24,'Pam Beesly',18000,'REJECTED',to_date('10-FEB-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (25,'Dwight Schrute',35000,'REJECTED',to_date('03-MAR-24','DD-MON-RR'),'PhD',48,4.95);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (26,'Kevin Malone',28000,'PENDING',to_date('10-MAR-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (28,'Stanley Hudson',42000,'REJECTED',to_date('12-MAR-24','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (29,'Grey Matter',53000,'APPROVED',to_date('10-MAR-25','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (30,'Peter Parker',15000,'APPROVED',to_date('08-MAR-25','DD-MON-RR'),'PhD',48,4.95);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (31,'John Snow',35000,'APPROVED',to_date('12-MAR-25','DD-MON-RR'),'PhD',48,4.95);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (32,'Oscar Martinez',30000,'PENDING',to_date('05-MAR-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (33,'Meredith Palmer',40000,'APPROVED',to_date('02-MAR-24','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (34,'Oscar Martinez',30000,'PENDING',to_date('05-MAR-24','DD-MON-RR'),'Postgraduate Degree',24,5.75);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (35,'Meredith Palmer',40000,'APPROVED',to_date('02-MAR-24','DD-MON-RR'),'Graduate Degree',36,6.25);
Insert into SYS.LOAN_APPLICATIONS (ID,STUDENT_NAME,LOAN_AMOUNT,STATUS,APPLICATION_DATE,PURPOSE,TERM,INTEREST_RATE) values (36,'Ryan Howard',25000,'REJECTED',to_date('10-MAR-24','DD-MON-RR'),'PhD',48,4.95);
